services:
  cognito:
    image: jagregory/cognito-local
    ports: 
      - "9229:9229"
    container_name: cognito-idp
    
  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    container_name: dynamodb