openapi: "3.0.1"
info:
  title: "DemoApi"
  version: "2022-07-10T12:24:48Z"
servers:
- url: "https://puwagapn1f.execute-api.us-east-2.amazonaws.com/{basePath}"
  variables:
    basePath:
      default: "/dev"
paths:
  /{proxy+}:
    x-amazon-apigateway-any-method:
      parameters:
      - name: "proxy"
        in: "path"
        required: true
        schema:
          type: "string"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: 
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SecurityFunction.Arn}/invocations"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        cacheNamespace: "85you4"
        cacheKeyParameters:
        - "method.request.path.proxy"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
components: {}
